# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps

In [13]:
#If adding external gkey:

#gkey = ""

gmaps.configure(api_key = gkey)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [14]:
# To read .csv back in...
weather_batch_all = pd.read_csv("..\WeatherPy\output_data\city_weather.csv", index_col = 0)
weather_batch_all.head(50)

,city,latitude,longitude,max_temp,humidity,cloud_cover,wind_speed,country,date
0,Kingisepp,58.92,2.854000e+01,32.90,93.0,99.0,5.64,RU,2021-04-24 01:47:24
1,Provideniya,53.36,-1.769900e+02,39.97,59.0,13.0,4.50,RU,2021-04-24 01:47:25
2,Negru voda,43.61,2.822000e+01,45.00,93.0,0.0,3.44,RO,2021-04-24 01:47:25
3,Paamiut,55.70,-5.055000e+01,32.11,77.0,2.0,4.52,GL,2021-04-24 01:37:53
4,Barrow,84.17,-1.438900e+02,28.40,69.0,1.0,5.12,US,2021-04-24 01:43:14
5,Huaihua,27.51,1.097100e+02,65.62,96.0,100.0,4.07,CN,2021-04-24 01:47:26
6,Mumford,3.81,-1.637090e-10,81.00,85.0,100.0,9.91,GH,2021-04-24 01:47:26
7,Pacific grove,30.61,-1.313900e+02,57.00,86.0,44.0,6.96,US,2021-04-24 01:41:16
8,Punta arenas,-69.78,-1.123600e+02,42.80,93.0,40.0,3.44,CL,2021-04-24 01:47:20
9,Visnes,57.99,2.050000e+00,41.00,70.0,75.0,16.11,NO,2021-04-24 01:47:26
10,Kieta,0.79,1.602800e+02,84.24,67.0,61.0,5.08,PG,2021-04-24 01:42:48
11,Tiksi,82.24,1.271000e+02,16.84,81.0,100.0,14.03,RU,2021-04-24 01:47:27
12,Rikitea,-28.88,-1.409900e+02,79.03,72.0,100.0,16.31,PF,2021-04-24 01:41:18
13,Cape town,-63.90,-1.100000e-01,59.00,82.0,0.0,9.22,ZA,2021-04-24 01:46:40
14,Mar del plata,-46.49,-4.741000e+01,66.20,72.0,90.0,6.91,AR,2021-04-24 01:47:28
15,Prado,-17.73,-3.667000e+01,74.79,85.0,14.0,5.41,BR,2021-04-24 01:47:28
16,Mataura,-55.83,-1.498500e+02,50.00,84.0,99.0,11.99,NZ,2021-04-24 01:47:29
17,Atuona,9.99,-1.301900e+02,80.38,78.0,23.0,23.85,PF,2021-04-24 01:47:29
18,Bluff,-67.99,1.714700e+02,50.00,84.0,88.0,11.99,NZ,2021-04-24 01:43:58
19,La ligua,-32.28,-7.131000e+01,56.64,87.0,7.0,1.39,CL,2021-04-24 01:47:30
20,Dingle,50.43,-1.968000e+01,89.60,53.0,93.0,8.23,PH,2021-04-24 01:46:12
21,Lugovskoy,56.96,6.441000e+01,44.60,42.0,0.0,8.95,RU,2021-04-24 01:47:30
22,Lebu,-32.66,-1.001700e+02,52.45,91.0,79.0,7.38,CL,2021-04-24 01:47:31
23,Vao,-28.14,1.654500e+02,75.92,74.0,57.0,11.14,NC,2021-04-24 01:43:11
24,Butaritari,18.81,1.643600e+02,81.37,78.0,100.0,6.62,KI,2021-04-24 01:37:51
25,Ruiru,-1.15,3.700000e+01,64.40,100.0,40.0,9.22,KE,2021-04-24 01:47:31
26,Arraial do cabo,-26.64,-3.648000e+01,73.72,77.0,61.0,11.74,BR,2021-04-24 01:47:32
27,Talcahuano,-30.63,-8.368000e+01,55.40,94.0,0.0,3.44,CL,2021-04-24 01:45:01
28,Saint george,27.01,-5.623000e+01,78.80,9.0,1.0,20.71,US,2021-04-24 01:45:09
29,Ratodero,27.79,6.824000e+01,73.40,60.0,0.0,2.19,PK,2021-04-24 01:47:32
30,Boiro,42.53,-8.990000e+00,59.00,94.0,100.0,5.53,ES,2021-04-24 01:47:32
31,Sao joao da barra,-28.32,-3.251000e+01,69.24,87.0,0.0,7.76,BR,2021-04-24 01:39:08
32,Hilo,15.19,-1.513300e+02,78.80,65.0,90.0,16.11,US,2021-04-24 01:45:44
33,Khatanga,73.21,1.032700e+02,33.26,96.0,100.0,19.64,RU,2021-04-24 01:41:36
34,Bethel,48.97,-1.659800e+02,57.20,24.0,1.0,4.61,US,2021-04-24 01:47:33
35,Klyuchi,55.38,1.609700e+02,38.57,62.0,3.0,6.67,RU,2021-04-24 01:47:33
36,Ayan,54.97,1.382400e+02,34.41,64.0,99.0,7.54,RU,2021-04-24 01:41:31
37,Westerland,54.76,8.580000e+00,41.00,85.0,75.0,1.01,DE,2021-04-24 01:47:34
38,Jacareacanga,-6.73,-5.877000e+01,74.37,97.0,100.0,1.14,BR,2021-04-24 01:47:34
39,Mugan,40.34,4.910000e+01,50.74,44.0,29.0,2.93,CN,2021-04-24 01:47:34
40,Ushuaia,-74.89,-5.256000e+01,42.80,93.0,75.0,13.80,AR,2021-04-24 01:39:26
41,Fairbanks,64.12,-1.462100e+02,57.99,21.0,1.0,5.75,US,2021-04-24 01:45:48
42,East london,-87.38,5.959000e+01,62.29,75.0,3.0,7.09,ZA,2021-04-24 01:42:45
43,Kapaa,15.36,-1.699300e+02,77.00,73.0,75.0,17.27,US,2021-04-24 01:47:35
44,Aromashevo,56.82,6.851000e+01,40.62,55.0,100.0,10.18,RU,2021-04-24 01:47:36
45,Hermanus,-89.01,-1.369000e+01,55.00,89.0,95.0,1.01,ZA,2021-04-24 01:43:56
46,Butembo,0.20,2.824000e+01,56.01,95.0,72.0,2.39,CD,2021-04-24 01:47:36
47,Pevek,84.40,1.699600e+02,18.66,85.0,63.0,2.01,RU,2021-04-24 01:40:55
48,Nome,71.72,-1.659300e+02,44.60,49.0,1.0,5.75,US,2021-04-24 01:47:37
49,Isangel,-20.40,1.741300e+02,86.00,70.0,75.0,5.75,VU,2021-04-24 01:44:13

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [15]:
# Access maps with unique API key
gmaps.configure(api_key = gkey)

In [16]:
# Store latitude and longitude in locations
locations = weather_batch_all[["latitude", "longitude"]]
humidity = weather_batch_all["humidity"]

# Customize the size of the figure
figure_layout = {
    'width': '800px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}


# Plot Heatmap
fig = gmaps.figure(center = (0, 0), zoom_level = 1.65, layout = figure_layout)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = humidity, 
                                 dissipating = True, 
                                 max_intensity = 200,
                                 point_radius = 40,
                                 opacity = 0.3)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [17]:
# Nice weather

nice_weather = weather_batch_all.loc[(weather_batch_all["humidity"] < 80) &
                                    (weather_batch_all["wind_speed"] < 10.0) &
                                    (weather_batch_all["cloud_cover"] < 50) &
                                    (weather_batch_all["max_temp"] > 70.0)]

nice_weather.head(50)

,city,latitude,longitude,max_temp,humidity,cloud_cover,wind_speed,country,date
29,Ratodero,27.79,68.24,73.40,60.0,0.0,2.19,PK,2021-04-24 01:47:32
50,Kudahuvadhoo,1.87,65.38,83.28,65.0,36.0,9.62,MV,2021-04-24 01:48:39
51,Nizwa,22.36,56.42,75.70,26.0,0.0,1.10,OM,2021-04-24 01:48:39
57,Busselton,-73.52,81.19,71.60,48.0,31.0,5.35,AU,2021-04-24 01:47:31
58,Hithadhoo,-1.12,67.08,82.45,70.0,17.0,5.10,MV,2021-04-24 01:48:41
71,Padang,-5.25,95.31,82.40,74.0,20.0,2.30,ID,2021-04-24 01:48:45
89,Quang ngai,14.96,109.49,89.83,55.0,32.0,3.22,VN,2021-04-24 01:48:50
104,Kupang,-12.29,124.51,84.65,64.0,2.0,6.82,ID,2021-04-24 01:49:55
105,Airai,7.45,140.86,74.17,48.0,5.0,3.13,TL,2021-04-24 01:47:53
123,Carnarvon,-24.18,112.85,73.40,43.0,2.0,8.05,AU,2021-04-24 01:50:01
133,San cristobal,-5.75,-87.15,84.20,65.0,20.0,2.30,VE,2021-04-24 01:43:01
135,Jati,-5.49,110.77,80.91,63.0,2.0,8.05,PK,2021-04-24 01:51:06
147,Tessalit,22.15,2.55,83.88,8.0,0.0,6.69,ML,2021-04-24 01:47:39
148,Kiunga,-6.17,138.92,91.63,56.0,25.0,1.79,PG,2021-04-24 01:48:39
160,Coahuayana,-0.06,-112.81,73.94,70.0,18.0,1.50,MX,2021-04-24 01:51:04
164,Cabo san lucas,12.18,-115.11,75.20,50.0,20.0,4.61,MX,2021-04-24 01:51:03
167,Natal,-3.44,-30.52,82.40,78.0,40.0,9.22,BR,2021-04-24 01:52:14
187,Sur,19.84,59.97,84.74,33.0,0.0,6.60,OM,2021-04-24 01:47:26
193,Vaini,-82.62,-168.35,86.00,74.0,20.0,6.91,TO,2021-04-24 01:47:59
202,Ocala,29.09,-82.11,73.40,64.0,20.0,9.22,US,2021-04-24 01:49:32
210,Ternate,3.54,130.05,84.16,73.0,20.0,7.52,ID,2021-04-24 01:51:06
217,Geraldton,-32.02,97.23,75.20,43.0,0.0,6.91,AU,2021-04-24 01:48:21
232,Hervey bay,-20.67,156.60,75.99,60.0,14.0,4.00,AU,2021-04-24 01:54:37
248,Gogrial,9.70,28.17,82.51,52.0,48.0,6.31,SS,2021-04-24 01:54:44
250,Korhogo,9.90,-5.75,79.75,49.0,18.0,5.57,CI,2021-04-24 01:54:45
262,Bayji,35.49,43.59,71.44,14.0,34.0,7.20,IQ,2021-04-24 01:55:50
265,Bodden town,20.15,-80.25,80.60,78.0,0.0,5.75,KY,2021-04-24 01:55:51
299,Vijapur,23.58,72.85,82.40,65.0,20.0,3.44,IN,2021-04-24 01:58:08
305,Moctezuma,29.56,-109.68,70.34,15.0,0.0,7.83,MX,2021-04-24 01:58:09
317,Thinadhoo,0.29,65.00,82.49,67.0,0.0,6.80,MV,2021-04-24 01:50:00
331,Pokhara,33.77,86.51,80.44,20.0,30.0,2.35,NP,2021-04-24 01:51:53
333,Salalah,13.59,60.68,82.40,74.0,40.0,1.14,OM,2021-04-24 01:51:55
348,Markapur,15.99,79.43,85.46,62.0,3.0,4.83,IN,2021-04-24 01:59:38
355,Labuhan,-11.46,99.89,82.31,70.0,2.0,4.99,ID,2021-04-24 01:47:47
361,Kalmunai,7.70,87.49,81.88,77.0,15.0,1.57,LK,2021-04-24 01:59:46
371,Katobu,-6.31,124.31,87.57,57.0,5.0,2.15,ID,2021-04-24 01:59:53
390,Gwadar,23.01,62.35,80.44,79.0,7.0,5.70,PK,2021-04-24 02:00:12
435,Karachi,24.98,66.48,82.40,34.0,0.0,4.61,PK,2021-04-24 02:00:36
437,Narasaraopet,16.34,79.95,85.24,69.0,9.0,5.88,IN,2021-04-24 01:58:40
460,Adrar,27.30,0.22,76.14,14.0,2.0,9.06,MR,2021-04-24 02:00:52
461,Sao filipe,6.78,-27.94,71.06,75.0,7.0,7.61,CV,2021-04-24 02:00:52
471,Turan,52.89,94.79,86.00,74.0,20.0,4.61,VN,2021-04-24 02:00:58
475,Alofi,-22.45,-170.16,86.00,70.0,32.0,9.22,NU,2021-04-24 02:01:01
481,Port antonio,19.04,-75.99,80.60,78.0,40.0,2.30,JM,2021-04-24 02:01:06
498,Atar,22.51,-13.04,77.50,15.0,0.0,6.60,MR,2021-04-24 02:01:11
499,Samarai,-10.38,154.01,84.54,72.0,48.0,9.71,PG,2021-04-24 02:01:11

In [18]:
hotel_df = nice_weather.copy()
hotel_df.reset_index(drop = True, inplace = True)
hotel_df.head()

,city,latitude,longitude,max_temp,humidity,cloud_cover,wind_speed,country,date
0,Ratodero,27.79,68.24,73.40,60.0,0.0,2.19,PK,2021-04-24 01:47:32
1,Kudahuvadhoo,1.87,65.38,83.28,65.0,36.0,9.62,MV,2021-04-24 01:48:39
2,Nizwa,22.36,56.42,75.70,26.0,0.0,1.10,OM,2021-04-24 01:48:39
3,Busselton,-73.52,81.19,71.60,48.0,31.0,5.35,AU,2021-04-24 01:47:31
4,Hithadhoo,-1.12,67.08,82.45,70.0,17.0,5.10,MV,2021-04-24 01:48:41

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [19]:
hotel_df["Hotel Name"] = ""
hotel_df.head()

,city,latitude,longitude,max_temp,humidity,cloud_cover,wind_speed,country,date,Hotel Name
0,Ratodero,27.79,68.24,73.40,60.0,0.0,2.19,PK,2021-04-24 01:47:32,
1,Kudahuvadhoo,1.87,65.38,83.28,65.0,36.0,9.62,MV,2021-04-24 01:48:39,
2,Nizwa,22.36,56.42,75.70,26.0,0.0,1.10,OM,2021-04-24 01:48:39,
3,Busselton,-73.52,81.19,71.60,48.0,31.0,5.35,AU,2021-04-24 01:47:31,
4,Hithadhoo,-1.12,67.08,82.45,70.0,17.0,5.10,MV,2021-04-24 01:48:41,

In [20]:
# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "language": "en",
    "key": gkey
}

for index, row in hotel_df.iterrows():
    # get lat, lon from df
    lat = row["latitude"]
    lon = row["longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat}, {lon}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    hotel_name = requests.get(base_url, params = params)
    
    # convert to json
    hotel_name_json = hotel_name.json()

    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_name_json["results"][1]["name"]
        print("Hotel found...updating DataFrame.")
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Hotel found...updating DataFrame.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Hotel found...updating DataFrame.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [21]:
hotel_df.head(46)

# Not many choices!

,city,latitude,longitude,max_temp,humidity,cloud_cover,wind_speed,country,date,Hotel Name
0,Ratodero,27.79,68.24,73.40,60.0,0.0,2.19,PK,2021-04-24 01:47:32,Mumtaz mangi hotel
1,Kudahuvadhoo,1.87,65.38,83.28,65.0,36.0,9.62,MV,2021-04-24 01:48:39,
2,Nizwa,22.36,56.42,75.70,26.0,0.0,1.10,OM,2021-04-24 01:48:39,
3,Busselton,-73.52,81.19,71.60,48.0,31.0,5.35,AU,2021-04-24 01:47:31,
4,Hithadhoo,-1.12,67.08,82.45,70.0,17.0,5.10,MV,2021-04-24 01:48:41,
5,Padang,-5.25,95.31,82.40,74.0,20.0,2.30,ID,2021-04-24 01:48:45,
6,Quang ngai,14.96,109.49,89.83,55.0,32.0,3.22,VN,2021-04-24 01:48:50,
7,Kupang,-12.29,124.51,84.65,64.0,2.0,6.82,ID,2021-04-24 01:49:55,
8,Airai,7.45,140.86,74.17,48.0,5.0,3.13,TL,2021-04-24 01:47:53,
9,Carnarvon,-24.18,112.85,73.40,43.0,2.0,8.05,AU,2021-04-24 01:50:01,
10,San cristobal,-5.75,-87.15,84.20,65.0,20.0,2.30,VE,2021-04-24 01:43:01,
11,Jati,-5.49,110.77,80.91,63.0,2.0,8.05,PK,2021-04-24 01:51:06,
12,Tessalit,22.15,2.55,83.88,8.0,0.0,6.69,ML,2021-04-24 01:47:39,
13,Kiunga,-6.17,138.92,91.63,56.0,25.0,1.79,PG,2021-04-24 01:48:39,
14,Coahuayana,-0.06,-112.81,73.94,70.0,18.0,1.50,MX,2021-04-24 01:51:04,
15,Cabo san lucas,12.18,-115.11,75.20,50.0,20.0,4.61,MX,2021-04-24 01:51:03,
16,Natal,-3.44,-30.52,82.40,78.0,40.0,9.22,BR,2021-04-24 01:52:14,
17,Sur,19.84,59.97,84.74,33.0,0.0,6.60,OM,2021-04-24 01:47:26,
18,Vaini,-82.62,-168.35,86.00,74.0,20.0,6.91,TO,2021-04-24 01:47:59,
19,Ocala,29.09,-82.11,73.40,64.0,20.0,9.22,US,2021-04-24 01:49:32,
20,Ternate,3.54,130.05,84.16,73.0,20.0,7.52,ID,2021-04-24 01:51:06,
21,Geraldton,-32.02,97.23,75.20,43.0,0.0,6.91,AU,2021-04-24 01:48:21,
22,Hervey bay,-20.67,156.60,75.99,60.0,14.0,4.00,AU,2021-04-24 01:54:37,
23,Gogrial,9.70,28.17,82.51,52.0,48.0,6.31,SS,2021-04-24 01:54:44,
24,Korhogo,9.90,-5.75,79.75,49.0,18.0,5.57,CI,2021-04-24 01:54:45,
25,Bayji,35.49,43.59,71.44,14.0,34.0,7.20,IQ,2021-04-24 01:55:50,
26,Bodden town,20.15,-80.25,80.60,78.0,0.0,5.75,KY,2021-04-24 01:55:51,
27,Vijapur,23.58,72.85,82.40,65.0,20.0,3.44,IN,2021-04-24 01:58:08,
28,Moctezuma,29.56,-109.68,70.34,15.0,0.0,7.83,MX,2021-04-24 01:58:09,
29,Thinadhoo,0.29,65.00,82.49,67.0,0.0,6.80,MV,2021-04-24 01:50:00,
30,Pokhara,33.77,86.51,80.44,20.0,30.0,2.35,NP,2021-04-24 01:51:53,
31,Salalah,13.59,60.68,82.40,74.0,40.0,1.14,OM,2021-04-24 01:51:55,
32,Markapur,15.99,79.43,85.46,62.0,3.0,4.83,IN,2021-04-24 01:59:38,Nasaraiah hotel
33,Labuhan,-11.46,99.89,82.31,70.0,2.0,4.99,ID,2021-04-24 01:47:47,
34,Kalmunai,7.70,87.49,81.88,77.0,15.0,1.57,LK,2021-04-24 01:59:46,
35,Katobu,-6.31,124.31,87.57,57.0,5.0,2.15,ID,2021-04-24 01:59:53,
36,Gwadar,23.01,62.35,80.44,79.0,7.0,5.70,PK,2021-04-24 02:00:12,
37,Karachi,24.98,66.48,82.40,34.0,0.0,4.61,PK,2021-04-24 02:00:36,
38,Narasaraopet,16.34,79.95,85.24,69.0,9.0,5.88,IN,2021-04-24 01:58:40,
39,Adrar,27.30,0.22,76.14,14.0,2.0,9.06,MR,2021-04-24 02:00:52,
40,Sao filipe,6.78,-27.94,71.06,75.0,7.0,7.61,CV,2021-04-24 02:00:52,
41,Turan,52.89,94.79,86.00,74.0,20.0,4.61,VN,2021-04-24 02:00:58,
42,Alofi,-22.45,-170.16,86.00,70.0,32.0,9.22,NU,2021-04-24 02:01:01,
43,Port antonio,19.04,-75.99,80.60,78.0,40.0,2.30,JM,2021-04-24 02:01:06,
44,Atar,22.51,-13.04,77.50,15.0,0.0,6.60,MR,2021-04-24 02:01:11,
45,Samarai,-10.38,154.01,84.54,72.0,48.0,9.71,PG,2021-04-24 02:01:11,

In [22]:
hotel_df["Hotel Name"].replace("", np.nan, inplace = True)
hotel_df.dropna(subset = ["Hotel Name"], inplace = True)

hotel_df.head()

,city,latitude,longitude,max_temp,humidity,cloud_cover,wind_speed,country,date,Hotel Name
0,Ratodero,27.79,68.24,73.40,60.0,0.0,2.19,PK,2021-04-24 01:47:32,Mumtaz mangi hotel
32,Markapur,15.99,79.43,85.46,62.0,3.0,4.83,IN,2021-04-24 01:59:38,Nasaraiah hotel

In [23]:
# NOTE: Do not change any of the code in this cell

### Had to change column names to match!!!###

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{city}</dd>
<dt>Country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["latitude", "longitude"]]

In [24]:
# Add marker layer ontop of heat map

# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wi…